export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';  
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';